action: eval-maniskill

model: smolvla
checkpoint: /work3/s234814/vla-robotics/models/smolvla_train_libero_all_a100.pt
simulator: maniskill
env_id: PegInsertionSide-v1
num_episodes: 20
wandb_project: vla-smolvla-maniskill
