"""Run LIBERO rollouts from a saved prompt-plan JSON.

This script only performs rollout execution using pre-generated prompts.
"""

from __future__ import annotations

import argparse
import csv
import json
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import cast

import torch

from vla.envs import make_env_factory
from vla.models.smolvla import SmolVLAPolicy
from vla.utils import get_device, seed_everything
from vla.utils.tensor import action_to_numpy

DEFAULT_SFT_CHECKPOINT = "HuggingFaceVLA/smolvla_libero"

PROMPT_VARIANT_TYPES: tuple[str, ...] = (
    "original",
    "politeness",
    "verb_paraphrase",
    "sentence_structure",
    "verbosity",
    "carefully",
    "quickly",
    "contrastive_negation",
    "do_not_move",
)


@dataclass
class PromptSpec:
    variant_type: str
    variant_index: int
    prompt: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--episodes", type=int, default=50)
    parser.add_argument("--max-steps", type=int, default=280)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--state-dim", type=int, default=8)
    parser.add_argument("--action-dim", type=int, default=7)
    parser.add_argument("--device", default="cuda", choices=["cuda", "cpu", "mps"])
    parser.add_argument("--output-dir", default="language_diagnostics/outputs")
    parser.add_argument(
        "--prompt-plan-path",
        required=True,
        help="Path to the saved prompt plan JSON generated by libero_prompt_variant_generate.py.",
    )
    parser.add_argument("--progress-every", type=int, default=10)
    parser.add_argument("--step-progress-every", type=int, default=0)
    return parser.parse_args()


def _fmt_seconds(seconds: float) -> str:
    s = int(max(0, seconds))
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    if h > 0:
        return f"{h:02d}:{m:02d}:{sec:02d}"
    return f"{m:02d}:{sec:02d}"


def load_prompt_plan(prompt_plan_path: Path) -> dict[str, object]:
    return json.loads(prompt_plan_path.read_text(encoding="utf-8"))


def _episode_seeds_for_task(global_seed: int, suite: str, task_id: int, num_episodes: int) -> list[int]:
    suite_offset = {"spatial": 0, "object": 100_000, "goal": 200_000, "long": 300_000}.get(suite, 400_000)
    base_seed = global_seed + suite_offset + task_id * 1_000
    return [base_seed + episode_index for episode_index in range(num_episodes)]


def _evaluate_prompt(
    policy: SmolVLAPolicy,
    suite: str,
    task_id: int,
    prompt: str,
    episode_seeds: list[int],
    max_steps: int,
    progress_every: int,
    step_progress_every: int,
    marker_label: str,
) -> list[dict[str, object]]:
    env_factory = make_env_factory("libero", suite=suite, state_dim=policy.state_dim, task_id=task_id)

    def _policy_fn(batch: dict) -> torch.Tensor:
        image_keys = sorted(k for k in batch if k.startswith("observation.images."))
        if not image_keys:
            raise ValueError(f"No image keys in batch. Keys: {list(batch.keys())}")
        cam_views: list[torch.Tensor] = []
        for key in image_keys:
            img = batch[key]
            if img.ndim in (4, 5):
                img = img[0]
            if img.ndim == 2:
                img = img.unsqueeze(0)
            cam_views.append(img)
        image = torch.stack(cam_views, dim=0) if len(cam_views) > 1 else cam_views[0]
        state = batch.get("observation.state")
        if state is not None and state.ndim == 2:
            state = state[0]
        return policy.predict_action(image, prompt, state)

    env = env_factory(0)
    try:
        capped_max_steps = min(max_steps, env.max_episode_steps)
        t0 = time.perf_counter()
        rollout_rows: list[dict[str, object]] = []

        for rollout_index, episode_seed in enumerate(episode_seeds):
            raw_obs, _info = env.reset(seed=episode_seed)
            ep_len = 0
            success = False
            ep_t0 = time.perf_counter()

            for step_idx in range(capped_max_steps):
                batch = env.obs_to_batch(raw_obs, device=policy.device)
                action_np = action_to_numpy(_policy_fn(batch))
                raw_obs, reward, terminated, truncated, info = env.step(action_np)
                _ = reward
                ep_len += 1

                step_done = step_idx + 1
                if step_progress_every > 0 and (
                    step_done == 1
                    or step_done == capped_max_steps
                    or step_done % step_progress_every == 0
                ):
                    ep_elapsed = time.perf_counter() - ep_t0
                    print(
                        f"        step-progress [{marker_label}] rollout={rollout_index + 1}/{len(episode_seeds)}, "
                        f"step={step_done}/{capped_max_steps}, elapsed={_fmt_seconds(ep_elapsed)}"
                    )

                if env.is_success(info):
                    success = True
                    break
                if terminated or truncated:
                    break

            rollout_rows.append(
                {
                    "rollout_index": rollout_index,
                    "episode_seed": episode_seed,
                    "success": success,
                    "episode_length": ep_len,
                }
            )

            done = rollout_index + 1
            if done == 1 or done == len(episode_seeds) or (progress_every > 0 and done % progress_every == 0):
                elapsed = time.perf_counter() - t0
                print(f"      progress [{marker_label}] {done}/{len(episode_seeds)} rollouts, elapsed={_fmt_seconds(elapsed)}")

        return rollout_rows
    finally:
        env.close()


def run_rollouts_from_prompt_file(
    policy: SmolVLAPolicy,
    prompt_payload: dict[str, object],
    args: argparse.Namespace,
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    rows: list[dict[str, object]] = []
    prompt_rows: list[dict[str, object]] = []

    tasks = cast(list[dict[str, object]], prompt_payload.get("tasks", []))
    total_prompt_runs = 0
    task_prompt_types: list[tuple[dict[str, object], list[str]]] = []

    for task in tasks:
        prompts = cast(dict[str, str], task["prompts"])
        prompt_types = [variant_type for variant_type in PROMPT_VARIANT_TYPES if variant_type in prompts]
        missing_types = [variant_type for variant_type in PROMPT_VARIANT_TYPES if variant_type not in prompts]

        if missing_types:
            suite = cast(str, task["suite"])
            task_id = cast(int, task["task_id"])
            print(
                f"  Task {task_id} ({suite}): skipping missing variant(s) {missing_types}; "
                f"running {len(prompt_types)} prompt(s) from saved plan"
            )

        task_prompt_types.append((task, prompt_types))
        total_prompt_runs += len(prompt_types)

    prompt_runs_done = 0

    for task, prompt_types in task_prompt_types:
        suite = cast(str, task["suite"])
        task_id = cast(int, task["task_id"])
        task_description = cast(str, task["task_description"])
        prompts = cast(dict[str, str], task["prompts"])

        episode_seeds = _episode_seeds_for_task(args.seed, suite, task_id, args.episodes)
        prompt_specs = [PromptSpec(variant_type=k, variant_index=0, prompt=prompts[k]) for k in prompt_types]

        print(f"  Task {task_id} ({suite}): evaluating {len(prompt_specs)} prompt(s)")

        for variant_type, prompt in prompts.items():
            prompt_rows.append(
                {
                    "suite": suite,
                    "task_id": task_id,
                    "task_description": task_description,
                    "variant_type": variant_type,
                    "prompt": prompt,
                }
            )

        for spec in prompt_specs:
            print(f"    [{spec.variant_type}:{spec.variant_index}] {spec.prompt}")
            prompt_start = time.perf_counter()
            marker_label = f"{suite}/task{task_id}/{spec.variant_type}"
            rollout_rows = _evaluate_prompt(
                policy=policy,
                suite=suite,
                task_id=task_id,
                prompt=spec.prompt,
                episode_seeds=episode_seeds,
                max_steps=args.max_steps,
                progress_every=args.progress_every,
                step_progress_every=args.step_progress_every,
                marker_label=marker_label,
            )

            for rollout in rollout_rows:
                rows.append(
                    {
                        "suite": suite,
                        "task_id": task_id,
                        "task_description": task_description,
                        "episode_seed_base": episode_seeds[0] if episode_seeds else None,
                        "variant_type": spec.variant_type,
                        "variant_index": spec.variant_index,
                        "prompt": spec.prompt,
                        "rollout_index": rollout["rollout_index"],
                        "episode_seed": rollout["episode_seed"],
                        "success": rollout["success"],
                        "episode_length": rollout["episode_length"],
                    }
                )

            prompt_runs_done += 1
            successes = sum(1 for r in rollout_rows if bool(r["success"]))
            lengths = [cast(int, r["episode_length"]) for r in rollout_rows]
            mean_len = sum(lengths) / max(len(lengths), 1)
            prompt_elapsed = time.perf_counter() - prompt_start
            print(
                f"    done [{marker_label}] prompt_run={prompt_runs_done}/{total_prompt_runs}, "
                f"success={successes}/{len(rollout_rows)}, mean_len={mean_len:.1f}, elapsed={_fmt_seconds(prompt_elapsed)}"
            )

    return rows, prompt_rows


def _save_rows_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = parse_args()
    run_start = time.perf_counter()
    seed_everything(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    prompt_plan_path = Path(args.prompt_plan_path)

    if not prompt_plan_path.exists():
        raise FileNotFoundError(f"Prompt plan file not found: {prompt_plan_path}")

    prompt_payload = load_prompt_plan(prompt_plan_path)
    device = get_device(args.device)
    policy = SmolVLAPolicy(
        checkpoint=DEFAULT_SFT_CHECKPOINT,
        action_dim=args.action_dim,
        state_dim=args.state_dim,
        device=str(device),
    )
    policy.eval()

    rows, prompt_rows = run_rollouts_from_prompt_file(policy=policy, prompt_payload=prompt_payload, args=args)

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "args": vars(args),
        "variant_types": list(PROMPT_VARIANT_TYPES),
        "prompt_plan_path": str(prompt_plan_path),
        "num_rollout_rows": len(rows),
        "num_prompt_rows": len(prompt_rows),
    }

    rows_path = output_dir / "libero_prompt_variant_rollouts_raw.csv"
    prompts_csv_path = output_dir / "libero_prompt_variant_prompts.csv"
    summary_path = output_dir / "libero_prompt_variant_rollouts_summary.json"
    _save_rows_csv(rows_path, rows)
    _save_rows_csv(prompts_csv_path, prompt_rows)
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print(f"Saved raw results to: {rows_path}")
    print(f"Saved prompts to: {prompts_csv_path}")
    print(f"Saved summary to: {summary_path}")
    print(f"Total wall time: {_fmt_seconds(time.perf_counter() - run_start)}")


if __name__ == "__main__":
    main()
